import React, { useState, useEffect } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "../index.css";
import Swipe from "../components/TinderSwipe";
import MovieListHeading from "../components/MovieListHeading";

//Random number generated to pick movie from list below//
const numberRandom = Math.floor(Math.random() * 500);

// Start of App function //
const Home = () => {
  // Set movies to empty state //
  const [movies, setMovies] = useState([]);

  // Start List of possible movies //
  const movieName = [
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Mary Poppins",
      Rating: "⭐⭐⭐⭐",
      Year: "1964",
    },
    {
      Link: "/Images/mr_bean.jpg",
      Movie_Name: "Mr Bean",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1990",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Brokeback Mountain",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Airplane!",
      Rating: "⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Seven Samurai",
      Rating: "⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/inception.jpg",
      Movie_Name: "Inception",
      Rating: "⭐⭐⭐⭐",
      Year: "2010",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "On the Waterfront",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/tom_and_jerry.jpg",
      Movie_Name: "Tom & Jerry",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rocky",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Fellowship of the Ring",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "A Clockwork Orange",
      Rating: "⭐⭐⭐⭐",
      Year: "1971",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "North by Northwest",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rocky",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Blade Runner",
      Rating: "⭐⭐⭐⭐",
      Year: "1982",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lion King",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Wall-E",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Slumdog Millionaire",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Bridge on the River Kwai",
      Rating: "⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Seven",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Singin' in the Rain",
      Rating: "⭐⭐⭐⭐",
      Year: "1952",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Pan's Labyrinth",
      Rating: "⭐⭐⭐⭐",
      Year: "2006",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Butch Cassidy and the Sundance Kid",
      Rating: "⭐⭐⭐⭐",
      Year: "1969",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "One Flew Over the Cuckoo's Nest",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/nun.jpg",
      Movie_Name: "The Nun",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Bonnie and Clyde",
      Rating: "⭐⭐⭐⭐",
      Year: "1963",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Toy Story",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Home Alone",
      Rating: "⭐⭐⭐⭐",
      Year: "1990",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Iron Man",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Slumdog Millionaire",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/joker.jpg",
      Movie_Name: "Joker",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Kissing Booth",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "On the Waterfront",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/conjuring.jpg",
      Movie_Name: "Conjuring",
      Rating: "⭐⭐⭐",
      Year: "2013",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Slumdog Millionaire",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/mr_bean.jpg",
      Movie_Name: "Mr Bean",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1990",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Return of the King",
      Rating: "⭐⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Psycho",
      Rating: "⭐⭐⭐⭐",
      Year: "1960",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Reservoir Dogs",
      Rating: "⭐⭐⭐⭐",
      Year: "1992",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Usual Suspects",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/inception.jpg",
      Movie_Name: "Inception",
      Rating: "⭐⭐⭐⭐",
      Year: "2010",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "All About Eve",
      Rating: "⭐⭐⭐⭐",
      Year: "1950",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "On the Waterfront",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/the_mauritanian.jpg",
      Movie_Name: "The Mauritanian",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Kissing Booth",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Alien",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "One Flew Over the Cuckoo's Nest",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "North by Northwest",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Bonnie and Clyde",
      Rating: "⭐⭐⭐⭐",
      Year: "1963",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Alien",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/inception.jpg",
      Movie_Name: "Inception",
      Rating: "⭐⭐⭐⭐",
      Year: "2010",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monster Hunter",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Wall-E",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ferris Bueller's Day Off",
      Rating: "⭐⭐⭐⭐",
      Year: "1986",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/minari.jpg",
      Movie_Name: "Minari",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lion King",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rocky",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/nun.jpg",
      Movie_Name: "The Nun",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/tom_and_jerry.jpg",
      Movie_Name: "Tom & Jerry",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Shining",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Bridge on the River Kwai",
      Rating: "⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Raging Bull",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "One Flew Over the Cuckoo's Nest",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Avatar",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Reservoir Dogs",
      Rating: "⭐⭐⭐⭐",
      Year: "1992",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monster Hunter",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Evil Dead",
      Rating: "⭐⭐⭐⭐",
      Year: "1981",
    },
    {
      Link: "/Images/triangle.jpg",
      Movie_Name: "Triangle",
      Rating: "⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/fast_furious.jpg",
      Movie_Name: "Fast & Furious",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Up",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Psycho",
      Rating: "⭐⭐⭐⭐",
      Year: "1960",
    },
    {
      Link: "/Images/judas_and_the_black_messiah.jpg",
      Movie_Name: "Judas And The Black Messiah",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Amelie",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "American Beauty",
      Rating: "⭐⭐⭐⭐",
      Year: "1999",
    },
    {
      Link: "/Images/minari.jpg",
      Movie_Name: "Minari",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Taxi Driver",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Return of the King",
      Rating: "⭐⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Terminator",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "All the President's Men",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/the_little_things.jpg",
      Movie_Name: "The Little Things",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "West Side Story",
      Rating: "⭐⭐⭐",
      Year: "1961",
    },
    {
      Link: "/Images/the_secret_garden.jpg",
      Movie_Name: "The Secret Garden",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/the_little_things.jpg",
      Movie_Name: "The Little Things",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/tom_and_jerry.jpg",
      Movie_Name: "Tom & Jerry",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Avatar",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Airplane!",
      Rating: "⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/the_little_things.jpg",
      Movie_Name: "The Little Things",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "All the President's Men",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Young Frankenstein",
      Rating: "⭐⭐⭐⭐",
      Year: "1974",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Empire Strikes Back",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/harrypotter.jpg",
      Movie_Name: "Harrypotter",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Slumdog Millionaire",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Butch Cassidy and the Sundance Kid",
      Rating: "⭐⭐⭐⭐",
      Year: "1969",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Home Alone",
      Rating: "⭐⭐⭐⭐",
      Year: "1990",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Princess Bride",
      Rating: "⭐⭐⭐⭐",
      Year: "1987",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "La La Land",
      Rating: "⭐⭐⭐⭐",
      Year: "2016",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Braveheart",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "When Harry Met Sally",
      Rating: "⭐⭐⭐⭐",
      Year: "1989",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Alien",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Home Alone",
      Rating: "⭐⭐⭐⭐",
      Year: "1990",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Psycho",
      Rating: "⭐⭐⭐⭐",
      Year: "1960",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Breakfast Club",
      Rating: "⭐⭐⭐⭐",
      Year: "1985",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Saving Private Ryan",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Singin' in the Rain",
      Rating: "⭐⭐⭐⭐",
      Year: "1952",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Slumdog Millionaire",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/gladiator.jpg",
      Movie_Name: "Gladiator",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Seven Samurai",
      Rating: "⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/mirrors.jpg",
      Movie_Name: "Mirrors",
      Rating: "⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "All About Eve",
      Rating: "⭐⭐⭐⭐",
      Year: "1950",
    },
    {
      Link: "/Images/conjuring.jpg",
      Movie_Name: "Conjuring",
      Rating: "⭐⭐⭐",
      Year: "2013",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Evil Dead",
      Rating: "⭐⭐⭐⭐",
      Year: "1981",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ferris Bueller's Day Off",
      Rating: "⭐⭐⭐⭐",
      Year: "1986",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Return of the King",
      Rating: "⭐⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/judas_and_the_black_messiah.jpg",
      Movie_Name: "Judas And The Black Messiah",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "North by Northwest",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Avatar",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Usual Suspects",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Toy Story",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Seven",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Big Lebowski",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Butch Cassidy and the Sundance Kid",
      Rating: "⭐⭐⭐⭐",
      Year: "1969",
    },
    {
      Link: "/Images/tom_and_jerry.jpg",
      Movie_Name: "Tom & Jerry",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Enter The Dragon",
      Rating: "⭐⭐⭐",
      Year: "1973",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Bonnie and Clyde",
      Rating: "⭐⭐⭐⭐",
      Year: "1963",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Brokeback Mountain",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "12 Angry Men",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Wall-E",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Terminator",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rocky",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Breakfast Club",
      Rating: "⭐⭐⭐⭐",
      Year: "1985",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Home Alone",
      Rating: "⭐⭐⭐⭐",
      Year: "1990",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Wall-E",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Up",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/tom_and_jerry.jpg",
      Movie_Name: "Tom & Jerry",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Terminator",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Blazing Saddles",
      Rating: "⭐⭐⭐⭐",
      Year: "1974",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Enter The Dragon",
      Rating: "⭐⭐⭐",
      Year: "1973",
    },
    {
      Link: "/Images/batman.jpg",
      Movie_Name: "Batman",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/gladiator.jpg",
      Movie_Name: "Gladiator",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Blazing Saddles",
      Rating: "⭐⭐⭐⭐",
      Year: "1974",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Usual Suspects",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/batman.jpg",
      Movie_Name: "Batman",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Sound of Music",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Evil Dead",
      Rating: "⭐⭐⭐⭐",
      Year: "1981",
    },
    {
      Link: "/Images/god_father.jpg",
      Movie_Name: "God Father",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1972",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Amelie",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Saving Private Ryan",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Brokeback Mountain",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/triangle.jpg",
      Movie_Name: "Triangle",
      Rating: "⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Kissing Booth",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Blade Runner",
      Rating: "⭐⭐⭐⭐",
      Year: "1982",
    },
    {
      Link: "/Images/conjuring.jpg",
      Movie_Name: "Conjuring",
      Rating: "⭐⭐⭐",
      Year: "2013",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Raging Bull",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rocky",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/harrypotter.jpg",
      Movie_Name: "Harrypotter",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Kissing Booth",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Reservoir Dogs",
      Rating: "⭐⭐⭐⭐",
      Year: "1992",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Pan's Labyrinth",
      Rating: "⭐⭐⭐⭐",
      Year: "2006",
    },
    {
      Link: "/Images/the_father.jpg",
      Movie_Name: "The Father",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Seven Samurai",
      Rating: "⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Iron Man",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Breaking News In Yuba County",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Pan's Labyrinth",
      Rating: "⭐⭐⭐⭐",
      Year: "2006",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Blazing Saddles",
      Rating: "⭐⭐⭐⭐",
      Year: "1974",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Brokeback Mountain",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/harrypotter.jpg",
      Movie_Name: "Harrypotter",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Seven",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Taxi Driver",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "A Clockwork Orange",
      Rating: "⭐⭐⭐⭐",
      Year: "1971",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Terminator",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Bridge on the River Kwai",
      Rating: "⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Brokeback Mountain",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Enter The Dragon",
      Rating: "⭐⭐⭐",
      Year: "1973",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Sound of Music",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Evil Dead",
      Rating: "⭐⭐⭐⭐",
      Year: "1981",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Fargo",
      Rating: "⭐⭐⭐⭐",
      Year: "2014",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Airplane!",
      Rating: "⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Return of the King",
      Rating: "⭐⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Breaking News In Yuba County",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/the_little_things.jpg",
      Movie_Name: "The Little Things",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Fellowship of the Ring",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Fargo",
      Rating: "⭐⭐⭐⭐",
      Year: "2014",
    },
    {
      Link: "/Images/mirrors.jpg",
      Movie_Name: "Mirrors",
      Rating: "⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Bridge on the River Kwai",
      Rating: "⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Fargo",
      Rating: "⭐⭐⭐⭐",
      Year: "2014",
    },
    {
      Link: "/Images/raya_and_the_last_dragon.jpg",
      Movie_Name: "Raya And The Last Dragon",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Amelie",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "All the President's Men",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/minari.jpg",
      Movie_Name: "Minari",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/nun.jpg",
      Movie_Name: "The Nun",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/inception.jpg",
      Movie_Name: "Inception",
      Rating: "⭐⭐⭐⭐",
      Year: "2010",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ferris Bueller's Day Off",
      Rating: "⭐⭐⭐⭐",
      Year: "1986",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Fargo",
      Rating: "⭐⭐⭐⭐",
      Year: "2014",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/batman.jpg",
      Movie_Name: "Batman",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Singin' in the Rain",
      Rating: "⭐⭐⭐⭐",
      Year: "1952",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Bonnie and Clyde",
      Rating: "⭐⭐⭐⭐",
      Year: "1963",
    },
    {
      Link: "/Images/tom_and_jerry.jpg",
      Movie_Name: "Tom & Jerry",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Sound of Music",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Avatar",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ghostbusters",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Up",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "North by Northwest",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Reservoir Dogs",
      Rating: "⭐⭐⭐⭐",
      Year: "1992",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "One Flew Over the Cuckoo's Nest",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Terminator",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Usual Suspects",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/gladiator.jpg",
      Movie_Name: "Gladiator",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Blade Runner",
      Rating: "⭐⭐⭐⭐",
      Year: "1982",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Amadeus",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Seven Samurai",
      Rating: "⭐⭐⭐",
      Year: "2003",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lion King",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Enter The Dragon",
      Rating: "⭐⭐⭐",
      Year: "1973",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Up",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Blazing Saddles",
      Rating: "⭐⭐⭐⭐",
      Year: "1974",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/god_father.jpg",
      Movie_Name: "God Father",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1972",
    },
    {
      Link: "/Images/nun.jpg",
      Movie_Name: "The Nun",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/conjuring.jpg",
      Movie_Name: "Conjuring",
      Rating: "⭐⭐⭐",
      Year: "2013",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Empire Strikes Back",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Bridge on the River Kwai",
      Rating: "⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Taxi Driver",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Toy Story",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Enter The Dragon",
      Rating: "⭐⭐⭐",
      Year: "1973",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rocky",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Empire Strikes Back",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Princess Bride",
      Rating: "⭐⭐⭐⭐",
      Year: "1987",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Big Lebowski",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Butch Cassidy and the Sundance Kid",
      Rating: "⭐⭐⭐⭐",
      Year: "1969",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Sound of Music",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/misbehaviour.jpg",
      Movie_Name: "Misbehaviour",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Raging Bull",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Bridge on the River Kwai",
      Rating: "⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Terminator",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/mr_bean.jpg",
      Movie_Name: "Mr Bean",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1990",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/god_father.jpg",
      Movie_Name: "God Father",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1972",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Close Encounters of the Third Kind",
      Rating: "⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/conjuring.jpg",
      Movie_Name: "Conjuring",
      Rating: "⭐⭐⭐",
      Year: "2013",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ghostbusters",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Big Lebowski",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Die Hard",
      Rating: "⭐⭐⭐⭐",
      Year: "1988",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Enter The Dragon",
      Rating: "⭐⭐⭐",
      Year: "1973",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Enter The Dragon",
      Rating: "⭐⭐⭐",
      Year: "1973",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Young Frankenstein",
      Rating: "⭐⭐⭐⭐",
      Year: "1974",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Alien",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Singin' in the Rain",
      Rating: "⭐⭐⭐⭐",
      Year: "1952",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Raging Bull",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Young Frankenstein",
      Rating: "⭐⭐⭐⭐",
      Year: "1974",
    },
    {
      Link: "/Images/nun.jpg",
      Movie_Name: "The Nun",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monster Hunter",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/fast_furious.jpg",
      Movie_Name: "Fast & Furious",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "12 Angry Men",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Up",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ferris Bueller's Day Off",
      Rating: "⭐⭐⭐⭐",
      Year: "1986",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Terminator",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/judas_and_the_black_messiah.jpg",
      Movie_Name: "Judas And The Black Messiah",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/gladiator.jpg",
      Movie_Name: "Gladiator",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/nun.jpg",
      Movie_Name: "The Nun",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Pan's Labyrinth",
      Rating: "⭐⭐⭐⭐",
      Year: "2006",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Fight Club",
      Rating: "⭐⭐⭐⭐",
      Year: "1999",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Slumdog Millionaire",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/batman.jpg",
      Movie_Name: "Batman",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Good Will Hunting",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ferris Bueller's Day Off",
      Rating: "⭐⭐⭐⭐",
      Year: "1986",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Singin' in the Rain",
      Rating: "⭐⭐⭐⭐",
      Year: "1952",
    },
    {
      Link: "/Images/joker.jpg",
      Movie_Name: "Joker",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Big Lebowski",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Psycho",
      Rating: "⭐⭐⭐⭐",
      Year: "1960",
    },
    {
      Link: "/Images/the_secret_garden.jpg",
      Movie_Name: "The Secret Garden",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Breaking News In Yuba County",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/judas_and_the_black_messiah.jpg",
      Movie_Name: "Judas And The Black Messiah",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "A Clockwork Orange",
      Rating: "⭐⭐⭐⭐",
      Year: "1971",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monster Hunter",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Groundhog Day",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/conjuring.jpg",
      Movie_Name: "Conjuring",
      Rating: "⭐⭐⭐",
      Year: "2013",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Braveheart",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "American Beauty",
      Rating: "⭐⭐⭐⭐",
      Year: "1999",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rear Window",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Big Lebowski",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "A Clockwork Orange",
      Rating: "⭐⭐⭐⭐",
      Year: "1971",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "American Beauty",
      Rating: "⭐⭐⭐⭐",
      Year: "1999",
    },
    {
      Link: "/Images/gladiator.jpg",
      Movie_Name: "Gladiator",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "La La Land",
      Rating: "⭐⭐⭐⭐",
      Year: "2016",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Eternal Sunshine of the Spotless Mind",
      Rating: "⭐⭐⭐⭐",
      Year: "2004",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "A Clockwork Orange",
      Rating: "⭐⭐⭐⭐",
      Year: "1971",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "American Beauty",
      Rating: "⭐⭐⭐⭐",
      Year: "1999",
    },
    {
      Link: "/Images/raya_and_the_last_dragon.jpg",
      Movie_Name: "Raya And The Last Dragon",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ferris Bueller's Day Off",
      Rating: "⭐⭐⭐⭐",
      Year: "1986",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Close Encounters of the Third Kind",
      Rating: "⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Groundhog Day",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/the_father.jpg",
      Movie_Name: "The Father",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/misbehaviour.jpg",
      Movie_Name: "Misbehaviour",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Slumdog Millionaire",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/the_father.jpg",
      Movie_Name: "The Father",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Sound of Music",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Breakfast Club",
      Rating: "⭐⭐⭐⭐",
      Year: "1985",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Wall-E",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "West Side Story",
      Rating: "⭐⭐⭐",
      Year: "1961",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "On the Waterfront",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/harrypotter.jpg",
      Movie_Name: "Harrypotter",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Shining",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Kissing Booth",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/minari.jpg",
      Movie_Name: "Minari",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Braveheart",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/inception.jpg",
      Movie_Name: "Inception",
      Rating: "⭐⭐⭐⭐",
      Year: "2010",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Taxi Driver",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/the_secret_garden.jpg",
      Movie_Name: "The Secret Garden",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/batman.jpg",
      Movie_Name: "Batman",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/minari.jpg",
      Movie_Name: "Minari",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Braveheart",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Die Hard",
      Rating: "⭐⭐⭐⭐",
      Year: "1988",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/conjuring.jpg",
      Movie_Name: "Conjuring",
      Rating: "⭐⭐⭐",
      Year: "2013",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Fargo",
      Rating: "⭐⭐⭐⭐",
      Year: "2014",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lion King",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Airplane!",
      Rating: "⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Braveheart",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/raya_and_the_last_dragon.jpg",
      Movie_Name: "Raya And The Last Dragon",
      Rating: "⭐⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rear Window",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Pan's Labyrinth",
      Rating: "⭐⭐⭐⭐",
      Year: "2006",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Bridge on the River Kwai",
      Rating: "⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Fellowship of the Ring",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Toy Story",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Vertigo",
      Rating: "⭐⭐⭐⭐",
      Year: "1958",
    },
    {
      Link: "/Images/the_secret_garden.jpg",
      Movie_Name: "The Secret Garden",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Princess Bride",
      Rating: "⭐⭐⭐⭐",
      Year: "1987",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Groundhog Day",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/triangle.jpg",
      Movie_Name: "Triangle",
      Rating: "⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Raging Bull",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Ferris Bueller's Day Off",
      Rating: "⭐⭐⭐⭐",
      Year: "1986",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "All the President's Men",
      Rating: "⭐⭐⭐⭐",
      Year: "1976",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "12 Angry Men",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1957",
    },
    {
      Link: "/Images/mirrors.jpg",
      Movie_Name: "Mirrors",
      Rating: "⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Groundhog Day",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Amelie",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Singin' in the Rain",
      Rating: "⭐⭐⭐⭐",
      Year: "1952",
    },
    {
      Link: "/Images/joker.jpg",
      Movie_Name: "Joker",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Avatar",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Shining",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/god_father.jpg",
      Movie_Name: "God Father",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "1972",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Taxi Driver",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/our_friend.jpg",
      Movie_Name: "Our Friend",
      Rating: "⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/batman.jpg",
      Movie_Name: "Batman",
      Rating: "⭐⭐⭐⭐",
      Year: "2005",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Toy Story",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Jurassic Park",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Up",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/mirrors.jpg",
      Movie_Name: "Mirrors",
      Rating: "⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Braveheart",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "A Clockwork Orange",
      Rating: "⭐⭐⭐⭐",
      Year: "1971",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Seven",
      Rating: "⭐⭐⭐⭐",
      Year: "1995",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Kissing Booth",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rear Window",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/fast_furious.jpg",
      Movie_Name: "Fast & Furious",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monster Hunter",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monty Python and The Holy Grail",
      Rating: "⭐⭐⭐⭐",
      Year: "1975",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Saving Private Ryan",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Rear Window",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "On the Waterfront",
      Rating: "⭐⭐⭐⭐",
      Year: "1954",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Doctor Zhivago",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Pan's Labyrinth",
      Rating: "⭐⭐⭐⭐",
      Year: "2006",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Fargo",
      Rating: "⭐⭐⭐⭐",
      Year: "2014",
    },
    {
      Link: "/Images/tom_and_jerry.jpg",
      Movie_Name: "Tom & Jerry",
      Rating: "⭐⭐",
      Year: "2021",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Beauty and the Beast",
      Rating: "⭐⭐⭐",
      Year: "2017",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Sound of Music",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Deer Hunter",
      Rating: "⭐⭐⭐⭐",
      Year: "1978",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Wall-E",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Monster Hunter",
      Rating: "⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Some Like It Hot",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/nun.jpg",
      Movie_Name: "The Nun",
      Rating: "⭐⭐⭐",
      Year: "2018",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Pan's Labyrinth",
      Rating: "⭐⭐⭐⭐",
      Year: "2006",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Airplane!",
      Rating: "⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Lord of the Rings: The Fellowship of the Ring",
      Rating: "⭐⭐⭐⭐",
      Year: "2001",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Die Hard",
      Rating: "⭐⭐⭐⭐",
      Year: "1988",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Amadeus",
      Rating: "⭐⭐⭐⭐",
      Year: "1984",
    },
    {
      Link: "/Images/titanic.jpg",
      Movie_Name: "Titanic",
      Rating: "⭐⭐⭐⭐",
      Year: "1997",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Almost Famous",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Bonnie and Clyde",
      Rating: "⭐⭐⭐⭐",
      Year: "1963",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Big Lebowski",
      Rating: "⭐⭐⭐⭐",
      Year: "1998",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Sound of Music",
      Rating: "⭐⭐⭐⭐",
      Year: "1965",
    },
    {
      Link: "/Images/the_secret_garden.jpg",
      Movie_Name: "The Secret Garden",
      Rating: "⭐⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Evil Dead",
      Rating: "⭐⭐⭐⭐",
      Year: "1981",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "North by Northwest",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Avatar",
      Rating: "⭐⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/joker.jpg",
      Movie_Name: "Joker",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2019",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Reservoir Dogs",
      Rating: "⭐⭐⭐⭐",
      Year: "1992",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "American Beauty",
      Rating: "⭐⭐⭐⭐",
      Year: "1999",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "North by Northwest",
      Rating: "⭐⭐⭐⭐",
      Year: "1959",
    },
    {
      Link: "/Images/the_courier.jpg",
      Movie_Name: "The Courier",
      Rating: "⭐⭐⭐",
      Year: "2020",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Groundhog Day",
      Rating: "⭐⭐⭐⭐",
      Year: "1993",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Alien",
      Rating: "⭐⭐⭐⭐",
      Year: "1979",
    },
    {
      Link: "/Images/triangle.jpg",
      Movie_Name: "Triangle",
      Rating: "⭐⭐⭐",
      Year: "2009",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Empire Strikes Back",
      Rating: "⭐⭐⭐⭐",
      Year: "1980",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "The Princess Bride",
      Rating: "⭐⭐⭐⭐",
      Year: "1987",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Memento",
      Rating: "⭐⭐⭐⭐",
      Year: "2000",
    },
    {
      Link: "/Images/ironman.jpg",
      Movie_Name: "Wall-E",
      Rating: "⭐⭐⭐⭐",
      Year: "2008",
    },
    {
      Link: "/Images/joker.jpg",
      Movie_Name: "Joker",
      Rating: "⭐⭐⭐⭐⭐",
      Year: "2019",
    },
  ];
  // End List of possible movies //

  //Function to take Movie_Name from list and pit it into API //
  const getMovieRequest = async (searchValue) => {
    movieName.forEach((el, index) => {});
    const url = `https://www.omdbapi.com/?s=${movieName[numberRandom].Movie_Name}&apikey=263d22d8`;
    const response = await fetch(url);
    const responseJson = await response.json();
    // Response is put into JSON format, sliced to only show first movie //
    if (responseJson.Search) {
      setMovies(responseJson.Search.slice(0, 1));
    }
  };
  // Runs function about with inputed api info //
  useEffect(() => {
    getMovieRequest(movieName[numberRandom].Movie_Name);
  }, []);

  // Return the generated info onto the page //
  return (
    <div className="container movie-app ">
      <div className="row d-flex align-items-center mt-4 mb-4">
        {/* Header Text */}
        <MovieListHeading heading="" />
      </div>
      <div style={{ display: "flex", justifyContent: "center" }}>
        {/* Swipe shows movie poster on page*/}
        <Swipe movies={movies} />
      </div>
    </div>
  );
};

export default Home;
